Repository RedisBloom/RedisBloom, pull requests merged in 2020-12, with the labels that each got.

#260 Fix Cuckoo filter compact cause deleted by mistake
  src/cuckoo.c
  tests/test-cuckoo.c
  tests/test-perf.c
Labels: Bug fix

#262 Activate codecov.yml
  codecov.yml
Labels: Coverage

#258 fix BFAofRewrite() save header`s iter not equal 1
  src/rebloom.c
Labels: bug
