Repository RedisBloom/RedisBloom, pull requests merged in 2020-10, with the labels that each got.

#234 docs: correct language for go client (isn't python) and use redisbloom.so instead of redisearch.so as example
  docs/Configuration.md
  docs/index.md
Labels: Documentation change

#230 link to paper
  src/topk.c
  src/topk.h
Labels: Documentation change

#241 Applied clang-format to src/* files. Failing CI if linter rules not followed
  .circleci/config.yml
  Makefile
  src/cf.c
  src/cms.c
  src/cms.h
  src/cuckoo.c
  src/cuckoo.h
  src/print_version.c
  src/rebloom.c
  src/redismodule.h
  src/rm_cms.c
  src/rm_topk.c
  src/sb.c
  src/study.c
  src/studybloomcms.c
  src/topk.c
  src/topk.h
  src/version.h
Labels: enhancement

#243 change Expansion-rate info for nonscaling to NULL
  src/rebloom.c
  tests/pytests.py
Labels: bug

#244 Config docs and CF.RESERVE dafault value
  docs/Configuration.md
  docs/Cuckoo_Commands.md
  src/rebloom.c
Labels: Documentation change
