Repository RedisBloom/RedisBloom, pull requests merged in 2021-02, with the labels that each got.

#276 Fixed minor typo.
  docs/Quick_Start.md
Labels: Documentation change

#279 Fixes for MacOS platform version 10.5 and 11.0
  Makefile
Labels: build issue

#281 Fixed leak: TopKRdbLoad L275 overwrites the heap allocated string causing a small leak on that scenario
  src/rm_topk.c
Labels: Bug fix
