Repository RedisBloom/RedisBloom, pull requests merged in 2021-11, with the labels that each got.

#362 Add NRedisBloom client library to the docs and readme file
  README.md
  docs/index.md
Labels: Documentation change

#370 Silence compilation warnings
  src/rebloom.c
Labels: build issue

#371 [BUG] Fix CF.SCANDUMP for cuckoo filter
  src/cf.c
  src/rebloom.c
  tests/flow/test_cuckoo.py
  tests/flow/test_overall.py
Labels: Bug fix

#374 ReplicateVerbatim for CF.LOADCHUNK similar to #309
  src/rebloom.c
Labels: bug

#377 Fixed benchmarks metric extraction
  tests/benchmarks/defaults.yml
Labels: skip-changelog

#378 cherry-pick benchmark automation to v2.2
  .circleci/config.yml
  Makefile
  tests/benchmarks/.gitignore
  tests/benchmarks/Readme.md
  tests/benchmarks/bf_add_cap10M_err0.001.yml
  tests/benchmarks/cf_add_cap10M.yml
  tests/benchmarks/cms_add_err0.001_prob0.01.yml
  tests/benchmarks/defaults.yml
  tests/benchmarks/requirements.txt
  tests/benchmarks/topk_incrby_k100.yml
Labels: benchmark, skip-changelog

#380 Add commands.json
  commands.json
Labels: Documentation change
