Repository RedisBloom/RedisBloom, pull requests merged in 2022-06, with the labels that each got.

#462 [BUG] check for missing parameters in cuckoo filter
  src/rebloom.c
  tests/flow/test_cuckoo.py
Labels: Bug fix

#434 Fix cf.insert crash when capacity < 0
  src/rebloom.c
  tests/flow/test_cuckoo.py
Labels: Bug fix

#469 [DOC] fix [param] -> [PARAM param]
  commands.json
Labels: Documentation change

#470 [2.2] remove excutables
  tests/unit/test-basic
  tests/unit/test-cuckoo
Labels: build issue

#465 Update tdigest.quantile.md
  docs/commands/tdigest.quantile.md
Labels: Documentation change, skip-changelog

#466 Update commands docs
  docs/commands/tdigest.add.md
  docs/commands/tdigest.cdf.md
  docs/commands/tdigest.create.md
  docs/commands/tdigest.info.md
  docs/commands/tdigest.max.md
  docs/commands/tdigest.merge.md
  docs/commands/tdigest.min.md
  docs/commands/tdigest.reset.md
  docs/commands/tdigest.trimmed_mean.md
Labels: Documentation change, skip-changelog
