Repository RedisBloom/RedisBloom, pull requests merged in 2022-09, with the labels that each got.

#532 TDIGEST.MERGE and TDIGEST.MERGESTORE are now a single command. TDIGEST.MERGE can now merge to itself.
  commands.json
  docs/commands/tdigest.merge.md
  docs/commands/tdigest.mergestore.md
  src/rm_tdigest.c
  tests/flow/test_tdigest.py
Labels: API change

#530 Introduce TDIGEST.RANK and TDIGEST.REVRANK commands
  commands.json
  docs/commands/tdigest.rank.md
  docs/commands/tdigest.revrank.md
  src/rm_tdigest.c
  tests/flow/test_tdigest.py
Labels: API change

#536 Added 'Memory usage' and 'Sum weights' fields to TDIGEST.INFO reply
  docs/commands/tdigest.info.md
  src/rm_tdigest.c
  tests/flow/test_tdigest.py
Labels: feature

#542 Fixed TDIGEST.MERGE benchmarks after API changes
  tests/benchmarks/tdigest_merge_2hist_1M_samples_comp100.yml
Labels: benchmark

#547 Fixed TDIGEST.ADD weight parameter details to match implementation
  docs/commands/tdigest.add.md
Labels: Documentation change, skip-changelog
