Repository RedisBloom/RedisBloom, pull requests merged in 2022-05, with the labels that each got.

#453 Added TDIGEST.MERGE, TDIGEST.QUANTILE benchmarks
  tests/benchmarks/defaults.yml
  tests/benchmarks/tdigest_add_comp100.yml
  tests/benchmarks/tdigest_merge_2hist_1M_samples_comp100.yml
  tests/benchmarks/tdigest_quantile_p50_1M_samples_comp100.yml
  tests/benchmarks/tdigest_quantile_p95_1M_samples_comp100.yml
  tests/benchmarks/tdigest_quantile_p99_1M_samples_comp100.yml
Labels: benchmark

#459 Fixed TOPK.LIST extra argument in docs
  commands.json
Labels: Documentation change

#450 [BUG] prevent freeze when TOPK.INCRBY a large value
  docs/commands/topk.incrby.md
  src/rm_topk.c
  tests/flow/test_topk.py
Labels: bug

#454 Fix for RedisBloom broken links
  docs/commands/tdigest.create.md
  docs/docs/_index.md
Labels: Documentation change

#463 Fixed docs reference to percentile vs quantile
  commands.json
  docs/commands/tdigest.quantile.md
  docs/commands/tdigest.trimmed_mean.md
Labels: Documentation change, skip-changelog
