Repository RedisBloom/RedisBloom, pull requests merged in 2022-07, with the labels that each got.

#480 [DOC] change `cf.check` to `cf.exists`
  docs/commands/cf.addnx.md
  docs/commands/cf.insertnx.md
Labels: Documentation change

#478 [BUG] use BFMemUsage instead of BFSize
  src/rebloom.c
  tests/flow/test_overall.py
Labels: Bug fix

#483 [BUG] fix init params for CF.RESERVE
  docs/docs/Configuration.md
  src/cuckoo.c
  src/rebloom.c
  tests/flow/test_cuckoo.py
Labels: Bug fix

#484 [2.2] fix init params for CF.RESERVE (#483)
  src/cuckoo.c
  src/rebloom.c
  src/version.h
  tests/cuckoo.py
Labels: cherry-pick

#486 [2.2] Print module version on RM_OnLoad (#485)
  Makefile
  src/rebloom.c
Labels: cherry-pick

#487 Added TDIGEST.MERGESTORE command and made TDIGEST.CREATE compression optional
  commands.json
  docs/commands/tdigest.create.md
  docs/commands/tdigest.merge.md
  docs/commands/tdigest.mergestore.md
  src/rm_tdigest.c
  tests/flow/test_tdigest.py
  wordlist
Labels: enhancement
