Repository RedisBloom/RedisBloom, pull requests merged in 2022-08, with the labels that each got.

#503 Use RM_String in TDIGEST.QUANTILE reply
  src/rm_tdigest.c
  tests/flow/test_tdigest.py
Labels: enhancement

#513 Fixing the spellcheck
  .github/spellcheck-settings.yml
  .github/wordlist.txt
  .github/workflows/spellcheck.yml
  README.md
Labels: maintenance

#516 Fixing docker login
  .circleci/config.yml
Labels: maintenance

#520 [T-DIGEST] add COMPRESSION keyword to TDIGEST.CREATE
  commands.json
  src/rm_tdigest.c
  tests/flow/test_tdigest.py
Labels: API change
